export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_CONTRACTOR = 'CREATE_CONTRACTOR';
export const FETCH_CONTRACTOR = 'FETCH_CONTRACTOR';
export const FETCH_CONTRACTORS = 'FETCH_CONTRACTORS';
export const CREATE_CONTRACTORS = 'FETCH_CONTRACTORS';
export const DELETE_CONTRACTOR = 'DELETE_CONTRACTOR';
export const EDIT_CONTRACTOR = 'EDIT_CONTRACTOR';

