export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_CONTRACTOR = 'CREATE_CONTRACTOR';
export const FETCH_CONTRACTOR = 'FETCH_CONTRACTOR';
export const FETCH_CONTRACTORS = 'FETCH_CONTRACTORS';
export const DELETE_CONTRACTOR = 'DELETE_CONTRACTOR';
export const EDIT_CONTRACTOR = 'EDIT_CONTRACTOR';

export const CREATE_LENDER = 'CREATE_LENDER';
export const FETCH_LENDER = 'FETCH_LENDER';
export const FETCH_LENDERS = 'FETCH_LENDERS';
export const DELETE_LENDER = 'DELETE_LENDER';
export const EDIT_LENDER = 'EDIT_LENDER';

export const CREATE_AGENT = 'CREATE_AGENT';
export const FETCH_AGENT = 'FETCH_AGENT';
export const FETCH_AGENTS = 'FETCH_AGENTS';
export const DELETE_AGENT = 'DELETE_AGENT';
export const EDIT_AGENT = 'EDIT_AGENT';

export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const FETCH_ADDRESS = 'FETCH_ADDRESS';
export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
